### ISSUE TITLE
Verify workshop works with current latest versions

### ISSUE THREAD

**Issue by timtebeek** [moderneinc/springboot-migration-workshop#11]
```[tasklist]
### Tasks
- [x] [Gradle Plugin Adventure](https://moderneinc.github.io/springboot-migration-workshop/docs/gradle-plugin-adventure/)
- [x] [Maven Plugin Adventure](https://moderneinc.github.io/springboot-migration-workshop/docs/maven-plugin-adventure/)
- [x] [Moderne CLI Adventure](https://moderneinc.github.io/springboot-migration-workshop/docs/moderne-cli-adventure/)
- [x] [Moderne platform Adventure](https://moderneinc.github.io/springboot-migration-workshop/docs/moderne-platform-adventure/)
- [ ] [Spring Boot Migrator Adventure](https://moderneinc.github.io/springboot-migration-workshop/docs/spring-boot-migrator-adventure/)
- [ ] [Spring Tools Adventure](https://moderneinc.github.io/springboot-migration-workshop/docs/spring-tools-adventure/)
```

**Comment by timtebeek** [comment]
Also done; although continuous with the new versions coming out.
